language: node_js
# sudo: required

node_js:
  - "8"
  - "9"
  - "10"

before_install:
  - npm install -g nyc
  - npm install -g codecov
  - npm install -g phantomjs

addons:
  chrome: stable # have Travis install Chrome stable.
