// generated by typexs-ng
import {APP_ROUTES} from './app.routes';
import {BrowserModule} from '@angular/platform-browser';
import {RouterModule} from '@angular/router';
import {ModuleWithProviders} from '@angular/core';
import {Type} from '@angular/core';
import {AdminModule} from '../admin/admin.module';
import {NavigatorModule} from '../navigator/navigator.module';
import {UserModule} from "typexs-auth/src/modules/user/user.module";

export const APP_MODULES: Array<Type<any> | ModuleWithProviders | any[]> = [
  BrowserModule,
  AdminModule,
  NavigatorModule,
  UserModule,
  RouterModule.forRoot(APP_ROUTES)
]
