// generated by typexs-ng
import { APP_ROUTES } from './app.routes';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule } from '@angular/router';
import { ModuleWithProviders } from '@angular/core';
import { Type } from '@angular/core';

export const APP_MODULES : Array<Type<any> | ModuleWithProviders | any[]> = [
  BrowserModule,
  RouterModule.forRoot(APP_ROUTES)
]
