import {Config, FileUtils, Inject, Log, RuntimeLoader} from '@typexs/base';
import {ModuleDescriptor} from 'commons-moduls';
import {NgMetaDataCollector} from '../libs/angular/NgMetaDataCollector';
// import {NgModuleBuilder} from '../libs/angular/NgModuleBuilder';
import * as glob from 'glob';
import {join} from 'path';
import * as _ from 'lodash';
import {ITemplateEntry} from '..';
import {IStylesheetEntry} from '../libs/angular/IStylesheetEntry';
import {NgModuleBuilder} from '../libs/angular/NgModuleBuilder';


export class Ng {

  command = 'ng [op]';
  aliases = 'ng';
  describe = 'Ng prebuild ';


  @Inject()
  collector: NgMetaDataCollector;

  @Inject('RuntimeLoader')
  loader: RuntimeLoader;


  builder(yargs: any) {
    return yargs;
  }

  async handler(argv: any) {
    const appName = Config.get('app.name', 'dummy');
    const appPath = Config.get('app.path', '.');

    switch (argv.op) {
      case 'build-modules':
        return this.ngBuild();
      case 'build-themes':
        return this.ngThemes();
    }
  }


  async ngThemes() {
    this.generateTemplateFile();
    this.generateStylesheetFile();
  }


  /**
   * Generate src/app/stylesheets.ts file
   *
   * @returns {Promise<void>}
   */
  private generateStylesheetFile() {
    const modules = this.loader.registry.modules();
    const stylesheets = [];

    let currentModule: ModuleDescriptor;

    for (const _module of modules) {
      const minmatch = '' + _module.path + '/?(src)/app/themes/**/*.+(css|less|sass|scss)';
      currentModule = _module;
      const files = glob.sync(minmatch);
      if (_.isEmpty(files)) {
        continue;
      }


      for (const file of files) {
        const strippedPath = file.replace(_module.path, '');
        const themePath = strippedPath.split('/app/themes/').pop();
        const themeName = themePath.split('/').shift();
        const fileName = themePath.split('/').pop();

        const matchResult = fileName.match(/^(.*)\.(override|append)\.(css|less|sass|scss)$/);
        if (matchResult && matchResult.length === 3) {
          const stylesheet: IStylesheetEntry = {
            theme: themeName,
            name: matchResult[1],
            subcontext: matchResult[2],
            type: matchResult[3],
            stylesheet: `require('./themes/${themePath}')`
          };
          stylesheets.push(stylesheet);
        }
      }
    }

    let content = JSON.stringify(stylesheets, null, 2);
    content = content.replace(/\"(require\(.*\))\"/g, '$1');
    const lines = ['/**', ' * GENERATED BY "typexs ng build-themes"',
      ' * MODIFICATIONS WILL GET LOST ON NEXT GENERATION', ' */'];

    if (currentModule.name === 'typexs-ng') {
      lines.push('import {IStylesheetEntry} from \'../libs/angular/IStylesheetEntry\';');
    } else {
      lines.push('import {IStylesheetEntry} from \'typexs-ng\';');
    }
    lines.push('');
    lines.push('export const STYLES: IStylesheetEntry[] =');
    lines.push(content + ';');

    content = lines.join('\n');

    const stylesheetFileName = join(currentModule.path, 'src', 'app', 'stylesheets.ts');
    FileUtils.writeFileSync(stylesheetFileName, content);
    Log.info('Updated ' + stylesheetFileName);
  }


  /**
   * Generate src/app/themes.ts file
   *
   * @returns {Promise<void>}
   */
  private generateTemplateFile() {
    const modules = this.loader.registry.modules();
    const templeted = [];

    let currentModule: ModuleDescriptor;

    for (const _module of modules) {
      const minmatch = '' + _module.path + '/?(src)/app/themes/**/*.html';
      currentModule = _module;
      const files = glob.sync(minmatch);
      if (_.isEmpty(files)) {
        continue;
      }


      for (const file of files) {
        const strippedPath = file.replace(_module.path, '');
        const themePath = strippedPath.split('/app/themes/').pop();
        const themeName = themePath.split('/').shift();
        const fileName = themePath.split('/').pop();

        const matchResult = fileName.match(/^(.*)\.(component)\.html$/);
        if (matchResult && matchResult.length === 3) {
          const template: ITemplateEntry = {
            theme: themeName,
            name: matchResult[1],
            type: matchResult[2],
            template: `require('./themes/${themePath}')`
          };
          templeted.push(template);
        }
      }
    }


    let content = JSON.stringify(templeted, null, 2);
    content = content.replace(/\"(require\(.*\))\"/g, '$1');
    const lines = ['/**', ' * GENERATED BY "typexs ng build-themes"',
      ' * MODIFICATIONS WILL GET LOST ON NEXT GENERATION', ' */'];

    if (currentModule.name === 'typexs-ng') {
      lines.push('import {ITemplateEntry} from \'../libs/angular/ITemplateEntry\';');
    } else {
      lines.push('import {ITemplateEntry} from \'typexs-ng\';');
    }
    lines.push('');
    lines.push('export const THEMES: ITemplateEntry[] =');
    lines.push(content + ';');

    content = lines.join('\n');

    const themeFileName = join(currentModule.path, 'src', 'app', 'themes.ts');
    FileUtils.writeFileSync(themeFileName, content);
    Log.info('Updated ' + themeFileName);

  }


  /**
   * Generate src/modules/app/app.used.modules.ts
   *
   * @returns {Promise<void>}
   */
  async ngBuild() {
    // TODO check if modules are enabled
    const modules = this.collector.collectNgModules();
    const builder = new NgModuleBuilder();
    builder.addModules(modules);

    const content = builder.build();

    await builder.save();
  }
}
