/**
 * GENERATED BY "typexs ng readRoutes-themes"
 * MODIFICATIONS WILL GET LOST ON NEXT GENERATION
 */
import {ITemplateEntry} from '../libs/angular/ITemplateEntry';

export const THEMES: ITemplateEntry[] =
[
  /*
  {
    "theme": "custom",
    "name": "nav-root",
    "type": "component",
    "template": require('./themes/custom/nav-root.component.html')
  }
  */
];
