// /**
//  * GENERATED BY "typexs ng build-themes"
//  * MODIFICATIONS WILL GET LOST ON NEXT GENERATION
//  */
// import {ITemplateEntry} from '@typexs/ng';
//
// export const THEMES: ITemplateEntry[] =
// [
//   /*
//   {
//     "theme": "custom",
//     "name": "nav-root",
//     "type": "component",
//     "template": require('./themes/custom/nav-root.component.html')
//   }
//   */
// ];
