/**  Autogenerated file with theme informations **/
import {ITemplateEntry} from "../libs/angular/ITemplateEntry";


export const themes: ITemplateEntry[] = [
  {
    module: 'navigator',
    name: 'nav-root',
    type: 'component',
    theme: 'custom',
    template: require('./themes/custom/nav-root.component.html')
  }
]


