

server:
  default:
    type: web
    framework: express
    host: localhost
    port: 4500
    routes:
      - type: routing_controller
        context: api
        routePrefix: api
      - type: static_files
        routePrefix: public
        path: public
